name: Ruby RSpec Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start MySQL
        run: docker compose up -d

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '.ruby-version'
          bundler-cache: false

      - name: Install dependencies and update Lockfile
        run: |
          bundle config set --local frozen false
          bundle install

      - name: Wait for MySQL to be ready
        run: docker compose exec -T mysql-real mysqladmin --wait=30 ping -h localhost

      - name: Run RuboCop
        run: |
          bundle exec rubocop

      - name: Run RSpec
        run: |
          bundle exec rspec
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root

      - name: Auto-commit Gemfile.lock
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update Gemfile.lock by GitHub Actions"
          file_pattern: 'Gemfile.lock'
